### ISSUE TITLE
A chunk isn't loading

### ISSUE THREAD

**Issue by AminoX99** [ZengineeringTeam/Create-101#10]
So I was playing this modpack and I traveled 200 blocks in a direction that I wasn't gone before, suddenly I saw a chunk that was like not loaded, like you could see the stones and ores under the ground.

Modpack version= Create 101-1.1.1
Forge version= 1.15.2 - 31.2.43
World-type= Biomes o plenty
btw I had a render distance of 16
and the only mod I added was optifine, nothing else

Optifine version= OptiFine HD U G1 pre30

and also I tried making a new world and the same thing happened again

There was no crashlog or something else.

I forgot to say that F3-A fixes this issue

Feel free to ask me if you need more specific information

**Comment by Snownee** [comment]
try removing Optifine?

**Comment by AminoX99** [comment]
Just tested without optifine on the same world and a new world, I can confirm this issue doesn't occur without optifine
