### ISSUE TITLE
Wrong crafting result from Mixer

### ISSUE THREAD

**Issue by GentlemanGnu** [ZengineeringTeam/Create-101#6]
Okay, so I've been playing the modpack for a while, and am quite enjoying it.

I got to the point of making Chromatic Compound in big batches.  I'm putting 8 stacks (512) of Polished Quartz, 8 stacks (512)  of Popped Chorus Fruit, and 24 stacks (1536) of Powdered Obsidian into drawers, and hoppering these into the mixer.

According to the recipes within JEI, I would expect to get 512 Chromatic compound out.  But I'm consistently getting 9x16 or 144 pieces.  

Is this a bug with the JEI display, or the mixer output?

**Comment by Snownee** [comment]
Will be fixed in 0.3
