### ISSUE TITLE
Bug about the backpack from quark

### ISSUE THREAD

**Issue by RodroKomodo** [ZengineeringTeam/Create-101#7]
When trying to move items to the 2x2crafting grid with the mouse, the game crash, here are the crash log and a video showing the demostration

https://drive.google.com/drive/folders/14XX-5GZV-3IddNJX1dfBKNPNJ2n9FWFy?usp=sharing

**Comment by Snownee** [comment]
https://github.com/Shadows-of-Fire/FastWorkbench/issues/51
