### ISSUE TITLE
Blaze rods only drop when player kills blaze

### ISSUE THREAD

**Issue by AraerTalsen** [ZengineeringTeam/Create-101#9]
Is this a mod, config setting, or bug? I've tested it with pistons, create drills, saws, and crushing wheels, and none will drop blaze rods. They will drop if the player kills them, however. To confirm, I was able to get blaze rods by throwing snowballs at blaze, but dispensing snowballs would not result in any drops. Other mobs will still drop their loot from automatic methods, it seems to only be blaze.

**Comment by Snownee** [comment]
It's a vanilla feature. You should use deployer to kill blaze.

And blaze rod and blaze powder have a recipe. Check JEI
